/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solinfori.vistas;


import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;
import solinfori.controlador.coordinadores.CoordinaPrimeraVez;
import solinfori.modelo.logica.Sesion;
import solinfori.vistas.Consultas.Agenda;
import solinfori.vistas.Paciente.Expedientes;
import solinfori.vistas.Paciente.PrimeraVez;
import solinfori.vistas.Paciente.SomatometriaYSV;

/**
 *
 * @author Maribel Marroquín - SOLINFORI
 */
public class Plataforma extends javax.swing.JFrame {
    
    private static final String rutaImg="/solinfori/img/Background_2.jpg";
    private Sesion sesion;
    /*private static final UsuariosVO usuario;*/
    
    /**
     * Creates new form Plataforma
     */
    public Plataforma() {
        initComponents();
        this.cv = new ConectorVistas(escritorio);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pumPaciente = new javax.swing.JPopupMenu();
        mPrimeraVez = new javax.swing.JMenuItem();
        mSomato = new javax.swing.JMenuItem();
        mExpedientes = new javax.swing.JMenuItem();
        mCertificado = new javax.swing.JMenuItem();
        pumConsultas = new javax.swing.JPopupMenu();
        mAgenda = new javax.swing.JMenuItem();
        mCorreo = new javax.swing.JMenuItem();
        pumFinanzas = new javax.swing.JPopupMenu();
        mNotasRemision = new javax.swing.JMenuItem();
        mFacturas = new javax.swing.JMenuItem();
        mCxc = new javax.swing.JMenuItem();
        mReportes = new javax.swing.JMenuItem();
        pumHerramientas = new javax.swing.JPopupMenu();
        mDatosFiscales = new javax.swing.JMenuItem();
        mDisenosPlantillas = new javax.swing.JMenuItem();
        mRespaldos = new javax.swing.JMenuItem();
        mBitacoraAcceso = new javax.swing.JMenuItem();
        mErrores = new javax.swing.JMenuItem();
        pumConfiguracion = new javax.swing.JPopupMenu();
        mConfiguraUsuarios = new javax.swing.JMenuItem();
        mConfiguraCorreo = new javax.swing.JMenuItem();
        pumAyuda = new javax.swing.JPopupMenu();
        mPreguntasFrecuentes = new javax.swing.JMenuItem();
        mTopicosAyuda = new javax.swing.JMenuItem();
        mVideotutoriales = new javax.swing.JMenuItem();
        mAcercaDe = new javax.swing.JMenuItem();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        dSalida = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        dBotonExit = new javax.swing.JButton();
        dBotonCSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        barraMenu = new javax.swing.JToolBar();
        mPacientes = new javax.swing.JButton();
        mConsultas = new javax.swing.JButton();
        mFinanzas = new javax.swing.JButton();
        mHerramientas = new javax.swing.JButton();
        mConfiguracion = new javax.swing.JButton();
        mAyuda = new javax.swing.JButton();
        mSalir = new javax.swing.JButton();
        aAgenda = new javax.swing.JButton();
        aPrimeraVez1 = new javax.swing.JButton();
        aSomatometria = new javax.swing.JButton();
        aCorreo = new javax.swing.JButton();
        aSalir = new javax.swing.JButton();
        aExpediente = new javax.swing.JButton();
        lUsuario = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ImageIcon icon = new ImageIcon(getClass().getResource(rutaImg));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        pumPaciente.setBackground(new java.awt.Color(25, 149, 173));
        pumPaciente.setForeground(new java.awt.Color(255, 255, 255));

        mPrimeraVez.setBackground(new java.awt.Color(25, 149, 173));
        mPrimeraVez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mPrimeraVez.setText("Primera Vez");
        mPrimeraVez.setContentAreaFilled(false);
        mPrimeraVez.setIconTextGap(15);
        mPrimeraVez.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mPrimeraVez.setMinimumSize(new java.awt.Dimension(107, 22));
        mPrimeraVez.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/iPrimeraVez_x70.png"))); // NOI18N
        mPrimeraVez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPrimeraVezActionPerformed(evt);
            }
        });
        pumPaciente.add(mPrimeraVez);

        mSomato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mSomato.setText("Somatometría y Signos Vitales");
        mSomato.setIconTextGap(15);
        mSomato.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mSomato.setMinimumSize(new java.awt.Dimension(107, 22));
        mSomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSomatoActionPerformed(evt);
            }
        });
        pumPaciente.add(mSomato);

        mExpedientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mExpedientes.setText("Expedientes Médicos");
        mExpedientes.setIconTextGap(15);
        mExpedientes.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExpedientesActionPerformed(evt);
            }
        });
        pumPaciente.add(mExpedientes);

        mCertificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mCertificado.setText("Certificado Médico");
        mCertificado.setIconTextGap(15);
        mCertificado.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumPaciente.add(mCertificado);

        mAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mAgenda.setText("Agenda");
        mAgenda.setIconTextGap(15);
        mAgenda.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAgendaActionPerformed(evt);
            }
        });
        pumConsultas.add(mAgenda);

        mCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mCorreo.setText("Correo de Atención");
        mCorreo.setIconTextGap(15);
        mCorreo.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumConsultas.add(mCorreo);

        mNotasRemision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mNotasRemision.setText("Notas de Remisión");
        mNotasRemision.setIconTextGap(15);
        mNotasRemision.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumFinanzas.add(mNotasRemision);

        mFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mFacturas.setText("Facturas");
        mFacturas.setIconTextGap(15);
        mFacturas.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumFinanzas.add(mFacturas);

        mCxc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mCxc.setText("Cuentas por Cobrar");
        mCxc.setIconTextGap(15);
        mCxc.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumFinanzas.add(mCxc);

        mReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mReportes.setText("Reportes");
        mReportes.setIconTextGap(15);
        mReportes.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumFinanzas.add(mReportes);

        mDatosFiscales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mDatosFiscales.setText("Datos Fiscales");
        mDatosFiscales.setIconTextGap(15);
        mDatosFiscales.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumHerramientas.add(mDatosFiscales);

        mDisenosPlantillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mDisenosPlantillas.setText("Diseño de Plantillas");
        mDisenosPlantillas.setIconTextGap(15);
        mDisenosPlantillas.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumHerramientas.add(mDisenosPlantillas);

        mRespaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mRespaldos.setText("Generar Respaldo");
        mRespaldos.setIconTextGap(15);
        mRespaldos.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumHerramientas.add(mRespaldos);

        mBitacoraAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mBitacoraAcceso.setText("Bitácora de uso del sistema");
        mBitacoraAcceso.setIconTextGap(15);
        mBitacoraAcceso.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumHerramientas.add(mBitacoraAcceso);

        mErrores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mErrores.setText("Reportes de errores");
        mErrores.setIconTextGap(15);
        mErrores.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumHerramientas.add(mErrores);

        mConfiguraUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mConfiguraUsuarios.setText("Configuración de Usuarios");
        mConfiguraUsuarios.setIconTextGap(15);
        mConfiguraUsuarios.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumConfiguracion.add(mConfiguraUsuarios);

        mConfiguraCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mConfiguraCorreo.setText("Configuración de Correo Electrónico");
        mConfiguraCorreo.setIconTextGap(15);
        mConfiguraCorreo.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumConfiguracion.add(mConfiguraCorreo);

        mPreguntasFrecuentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mPreguntasFrecuentes.setText("Preguntas Frecuentes");
        mPreguntasFrecuentes.setIconTextGap(15);
        mPreguntasFrecuentes.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumAyuda.add(mPreguntasFrecuentes);

        mTopicosAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mTopicosAyuda.setText("Tópicos de ayuda");
        mTopicosAyuda.setIconTextGap(15);
        mTopicosAyuda.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumAyuda.add(mTopicosAyuda);

        mVideotutoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mVideotutoriales.setText("Videotutoriales");
        mVideotutoriales.setIconTextGap(15);
        mVideotutoriales.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumAyuda.add(mVideotutoriales);

        mAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x17.png"))); // NOI18N
        mAcercaDe.setText("Acerca de ...");
        mAcercaDe.setIconTextGap(15);
        mAcercaDe.setMargin(new java.awt.Insets(10, 10, 10, 10));
        pumAyuda.add(mAcercaDe);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setTitle("Agenda");
        jInternalFrame1.setMaximumSize(new java.awt.Dimension(700, 400));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(700, 400));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(700, 400));
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        dSalida.setAlwaysOnTop(true);
        dSalida.setMinimumSize(new java.awt.Dimension(353, 90));
        dSalida.setResizable(false);

        jLabel2.setText("¿Desea realmente salir del sistema SAICMed?");

        dBotonExit.setText("Si");
        dBotonExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dBotonExit.setContentAreaFilled(false);
        dBotonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBotonExitActionPerformed(evt);
            }
        });

        dBotonCSalir.setText("Cancelar");
        dBotonCSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dBotonCSalir.setContentAreaFilled(false);
        dBotonCSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBotonCSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dSalidaLayout = new javax.swing.GroupLayout(dSalida.getContentPane());
        dSalida.getContentPane().setLayout(dSalidaLayout);
        dSalidaLayout.setHorizontalGroup(
            dSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dSalidaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dBotonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dBotonCSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap())
        );
        dSalidaLayout.setVerticalGroup(
            dSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dBotonExit)
                    .addComponent(dBotonCSalir))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(161, 214, 226));

        cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cerrar.setForeground(new java.awt.Color(25, 149, 173));
        cerrar.setText("X");
        cerrar.setToolTipText("Cerrar");
        cerrar.setBorder(null);
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        minimizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minimizar.setForeground(new java.awt.Color(25, 149, 173));
        minimizar.setText("-");
        minimizar.setToolTipText("Minimizar");
        minimizar.setBorder(null);
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(25, 149, 173));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Consultorio del Dr. José Luis Marroquín Caratachea");

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));

        barraMenu.setBackground(new java.awt.Color(255, 255, 255));
        barraMenu.setBorder(null);
        barraMenu.setFloatable(false);
        barraMenu.setRollover(true);
        barraMenu.setBorderPainted(false);

        mPacientes.setBackground(new java.awt.Color(255, 255, 255));
        mPacientes.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        mPacientes.setMnemonic(KeyEvent.VK_P);
        mPacientes.setText("Pacientes");
        mPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mPacientes.setDisplayedMnemonicIndex(0);
        mPacientes.setFocusCycleRoot(true);
        mPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mPacientes.setMargin(new java.awt.Insets(14, 14, 14, 14));
        mPacientes.setRequestFocusEnabled(false);
        mPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPacientesMouseClicked(evt);
            }
        });
        barraMenu.add(mPacientes);

        mConsultas.setBackground(new java.awt.Color(255, 255, 255));
        mConsultas.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        mConsultas.setMnemonic('C');
        mConsultas.setText("Consultas");
        mConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mConsultas.setFocusCycleRoot(true);
        mConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mConsultas.setMargin(new java.awt.Insets(14, 14, 14, 14));
        mConsultas.setRequestFocusEnabled(false);
        mConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mConsultasMouseClicked(evt);
            }
        });
        barraMenu.add(mConsultas);

        mFinanzas.setBackground(new java.awt.Color(255, 255, 255));
        mFinanzas.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        mFinanzas.setMnemonic('F');
        mFinanzas.setText("Finanzas");
        mFinanzas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mFinanzas.setFocusCycleRoot(true);
        mFinanzas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mFinanzas.setMargin(new java.awt.Insets(14, 14, 14, 14));
        mFinanzas.setRequestFocusEnabled(false);
        mFinanzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mFinanzasMouseClicked(evt);
            }
        });
        barraMenu.add(mFinanzas);

        mHerramientas.setBackground(new java.awt.Color(255, 255, 255));
        mHerramientas.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        mHerramientas.setMnemonic('H');
        mHerramientas.setText("Herramientas del Sistema");
        mHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mHerramientas.setFocusCycleRoot(true);
        mHerramientas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mHerramientas.setMargin(new java.awt.Insets(14, 14, 14, 14));
        mHerramientas.setRequestFocusEnabled(false);
        mHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mHerramientasMouseClicked(evt);
            }
        });
        barraMenu.add(mHerramientas);

        mConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        mConfiguracion.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        mConfiguracion.setMnemonic('N');
        mConfiguracion.setText("Configuración");
        mConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mConfiguracion.setFocusCycleRoot(true);
        mConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mConfiguracion.setMargin(new java.awt.Insets(14, 14, 14, 14));
        mConfiguracion.setRequestFocusEnabled(false);
        mConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mConfiguracionMouseClicked(evt);
            }
        });
        barraMenu.add(mConfiguracion);

        mAyuda.setBackground(new java.awt.Color(255, 255, 255));
        mAyuda.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        mAyuda.setMnemonic('A');
        mAyuda.setText("Ayuda");
        mAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mAyuda.setFocusCycleRoot(true);
        mAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mAyuda.setMargin(new java.awt.Insets(14, 14, 14, 14));
        mAyuda.setRequestFocusEnabled(false);
        mAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mAyudaMouseClicked(evt);
            }
        });
        barraMenu.add(mAyuda);

        mSalir.setBackground(new java.awt.Color(255, 255, 255));
        mSalir.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        mSalir.setMnemonic('S');
        mSalir.setText("Salir");
        mSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mSalir.setFocusCycleRoot(true);
        mSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mSalir.setMargin(new java.awt.Insets(14, 14, 14, 14));
        mSalir.setRequestFocusEnabled(false);
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        barraMenu.add(mSalir);

        aAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/iAgenda_x70.png"))); // NOI18N
        aAgenda.setToolTipText("Agenda");
        aAgenda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aAgenda.setBorderPainted(false);
        aAgenda.setContentAreaFilled(false);
        aAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aAgenda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/pressed/iAgenda_x70_pressed.png"))); // NOI18N
        aAgenda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iAgenda_x70_rollover.png"))); // NOI18N
        aAgenda.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iAgenda_x70_rollover.png"))); // NOI18N
        aAgenda.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iAgenda_x70_rollover.png"))); // NOI18N
        aAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAgendaActionPerformed(evt);
            }
        });

        aPrimeraVez1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/iPrimeraVez_x70.png"))); // NOI18N
        aPrimeraVez1.setToolTipText("Paciente Primera Vez");
        aPrimeraVez1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aPrimeraVez1.setBorderPainted(false);
        aPrimeraVez1.setContentAreaFilled(false);
        aPrimeraVez1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aPrimeraVez1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aPrimeraVez1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/pressed/iPrimeraVez_x70_pressed.png"))); // NOI18N
        aPrimeraVez1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iPrimeraVez_x70_rollover.png"))); // NOI18N
        aPrimeraVez1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iPrimeraVez_x70_rollover.png"))); // NOI18N
        aPrimeraVez1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iPrimeraVez_x70_rollover.png"))); // NOI18N
        aPrimeraVez1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPrimeraVez1ActionPerformed(evt);
            }
        });

        aSomatometria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/iSomato_x70.png"))); // NOI18N
        aSomatometria.setToolTipText("Somatometría");
        aSomatometria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aSomatometria.setBorderPainted(false);
        aSomatometria.setContentAreaFilled(false);
        aSomatometria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aSomatometria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aSomatometria.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/pressed/iSomato_x70_pressed.png"))); // NOI18N
        aSomatometria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iSomato_x70_rollover.png"))); // NOI18N
        aSomatometria.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iSomato_x70_rollover.png"))); // NOI18N
        aSomatometria.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iSomato_x70_rollover.png"))); // NOI18N
        aSomatometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSomatometriaActionPerformed(evt);
            }
        });

        aCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/iCorreo_x70.png"))); // NOI18N
        aCorreo.setToolTipText("Correo de Atención");
        aCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aCorreo.setBorderPainted(false);
        aCorreo.setContentAreaFilled(false);
        aCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aCorreo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/pressed/iCorreo_x70_pressed.png"))); // NOI18N
        aCorreo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iCorreo_x70_rollover.png"))); // NOI18N
        aCorreo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iCorreo_x70_rollover.png"))); // NOI18N
        aCorreo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iCorreo_x70_rollover.png"))); // NOI18N

        aSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/iSalir_x70.png"))); // NOI18N
        aSalir.setToolTipText("Salir");
        aSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aSalir.setBorderPainted(false);
        aSalir.setContentAreaFilled(false);
        aSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/pressed/iSalir_x70_pressed.png"))); // NOI18N
        aSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iSalir_x70_rollover.png"))); // NOI18N
        aSalir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iSalir_x70_rollover.png"))); // NOI18N
        aSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iSalir_x70_rollover.png"))); // NOI18N
        aSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSalirActionPerformed(evt);
            }
        });

        aExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/iExpediente_x70.png"))); // NOI18N
        aExpediente.setToolTipText("Expedientes Médicos");
        aExpediente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aExpediente.setBorderPainted(false);
        aExpediente.setContentAreaFilled(false);
        aExpediente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aExpediente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aExpediente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/pressed/iExpediente_x70_pressed.png"))); // NOI18N
        aExpediente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iExpediente_x70_rollover.png"))); // NOI18N
        aExpediente.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iExpediente_x70_rollover.png"))); // NOI18N
        aExpediente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/rollover/iExpediente_x70_rollover.png"))); // NOI18N

        lUsuario.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        lUsuario.setForeground(new java.awt.Color(25, 149, 173));
        lUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lUsuario.setText("Administrador");
        lUsuario.setToolTipText("Sesión de Usuario");

        titulo1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        titulo1.setForeground(new java.awt.Color(25, 149, 173));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo1.setText("Usuario:");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aPrimeraVez1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aExpediente)
                .addGap(18, 18, 18)
                .addComponent(aAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aSomatometria)
                .addGap(18, 18, 18)
                .addComponent(aCorreo)
                .addGap(18, 18, 18)
                .addComponent(aSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addComponent(barraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(aAgenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aSomatometria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aPrimeraVez1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(248, 248, 248))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(escritorio);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 149, 173));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("  SIACMed   -   Sistema Integral para la Administración de Consultorios Médicos");
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("S   O   L   I   N   F   O   R   I   .   C   O   M    ");
        jLabel3.setRequestFocusEnabled(false);
        jLabel3.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(minimizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed
    
    private void dialogCerrar(){
        dSalida.setResizable(false);
        dSalida.setTitle("Salir de SIACMed.");
        dSalida.setSize(400,120);
        dSalida.setLocationRelativeTo(this); //JUSTO DESPUES DE MI "setSize()"
        dSalida.setVisible(true);
    }
    
    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        dialogCerrar();
    }//GEN-LAST:event_cerrarActionPerformed

    private void dBotonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBotonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_dBotonExitActionPerformed

    private void dBotonCSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBotonCSalirActionPerformed
        // TODO add your handling code here:
        dSalida.dispose();
    }//GEN-LAST:event_dBotonCSalirActionPerformed

    private void aSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSalirActionPerformed
        // TODO add your handling code here:
        dialogCerrar();
    }//GEN-LAST:event_aSalirActionPerformed

    private void mPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPacientesMouseClicked
        // TODO add your handling code here:
        MouseEvent eventoMouse=new MouseEvent(mPacientes, 0, evt.getWhen(), KeyEvent.VK_UNDEFINED, 10,jPanel1.getY()+mPacientes.getY()+40 , 1, true);
        checkPopup1(eventoMouse);
    }//GEN-LAST:event_mPacientesMouseClicked

    private void mConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mConsultasMouseClicked
        // TODO add your handling code here:
        MouseEvent eventoMouse=new MouseEvent(mConsultas, 0, evt.getWhen(), KeyEvent.VK_UNDEFINED, 10,jPanel1.getY()+mConsultas.getY()+40 , 1, true);
        checkPopup2(eventoMouse);
    }//GEN-LAST:event_mConsultasMouseClicked

    private void mFinanzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mFinanzasMouseClicked
        // TODO add your handling code here:
        MouseEvent eventoMouse=new MouseEvent(mFinanzas, 0, evt.getWhen(), KeyEvent.VK_UNDEFINED, 10,jPanel1.getY()+mFinanzas.getY()+40 , 1, true);
        checkPopup3(eventoMouse);
    }//GEN-LAST:event_mFinanzasMouseClicked

    private void mHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mHerramientasMouseClicked
        // TODO add your handling code here:
        MouseEvent eventoMouse=new MouseEvent(mHerramientas, 0, evt.getWhen(), KeyEvent.VK_UNDEFINED, 10,jPanel1.getY()+mHerramientas.getY()+40 , 1, true);
        checkPopup4(eventoMouse);
    }//GEN-LAST:event_mHerramientasMouseClicked

    private void mConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mConfiguracionMouseClicked
        // TODO add your handling code here:
        MouseEvent eventoMouse=new MouseEvent(mConfiguracion, 0, evt.getWhen(), KeyEvent.VK_UNDEFINED, 10,jPanel1.getY()+mConfiguracion.getY()+40 , 1, true);
        checkPopup5(eventoMouse);
    }//GEN-LAST:event_mConfiguracionMouseClicked

    private void mAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mAyudaMouseClicked
        // TODO add your handling code here:
        MouseEvent eventoMouse=new MouseEvent(mAyuda, 0, evt.getWhen(), KeyEvent.VK_UNDEFINED, 10,jPanel1.getY()+mAyuda.getY()+40 , 1, true);
        checkPopup6(eventoMouse);
    }//GEN-LAST:event_mAyudaMouseClicked

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
        // TODO add your handling code here:
        dialogCerrar();
    }//GEN-LAST:event_mSalirMouseClicked

    private void mExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExpedientesActionPerformed
        // TODO add your handling code here:
        cv.jInExpedientes(Expedientes.getInstancia());
    }//GEN-LAST:event_mExpedientesActionPerformed

    private void mPrimeraVezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPrimeraVezActionPerformed
        // TODO add your handling code here:
        cv.jInPrimeraVez(PrimeraVez.getInstancia(sesion));
        
    }//GEN-LAST:event_mPrimeraVezActionPerformed

    private void aPrimeraVez1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPrimeraVez1ActionPerformed
        // TODO add your handling code here:
        cv.jInPrimeraVez(PrimeraVez.getInstancia(sesion));
        
    }//GEN-LAST:event_aPrimeraVez1ActionPerformed

    private void mAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAgendaActionPerformed
        // TODO add your handling code here:
        cv.jInAgenda(Agenda.getInstancia());
    }//GEN-LAST:event_mAgendaActionPerformed

    private void aAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAgendaActionPerformed
        // TODO add your handling code here:
        cv.jInAgenda(Agenda.getInstancia());
    }//GEN-LAST:event_aAgendaActionPerformed

    private void mSomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSomatoActionPerformed
        // TODO add your handling code here:
        cv.jInSomatoSV(SomatometriaYSV.getInstance());
    }//GEN-LAST:event_mSomatoActionPerformed

    private void aSomatometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSomatometriaActionPerformed
        // TODO add your handling code here:
        cv.jInSomatoSV(SomatometriaYSV.getInstance());
    }//GEN-LAST:event_aSomatometriaActionPerformed
                             
    private void checkPopup1(MouseEvent e) {
         pumPaciente.show(e.getComponent(), e.getX(), e.getY());
    }
    
    private void checkPopup2(MouseEvent e) {
         pumConsultas.show(e.getComponent(), e.getX(), e.getY());
    }
    
    private void checkPopup3(MouseEvent e) {
         pumFinanzas.show(e.getComponent(), e.getX(), e.getY());
    }
    
    private void checkPopup4(MouseEvent e) {
         pumHerramientas.show(e.getComponent(), e.getX(), e.getY());
    }
    
    private void checkPopup5(MouseEvent e) {
         pumConfiguracion.show(e.getComponent(), e.getX(), e.getY());
    }
    
    private void checkPopup6(MouseEvent e) {
         pumAyuda.show(e.getComponent(), e.getX(), e.getY());
    }

    /**
     *
     * ------------------------------------------Getters and Setters------------------------------------
     * @return
     */
    
    public ConectorVistas getCv() {
        return cv;
    }

    public void setCv(ConectorVistas cv) {
        this.cv = cv;
    }

    public JButton getaAgenda() {
        return aAgenda;
    }

    public void setaAgenda(JButton aAgenda) {
        this.aAgenda = aAgenda;
    }

    public JButton getaCorreo() {
        return aCorreo;
    }

    public void setaCorreo(JButton aCorreo) {
        this.aCorreo = aCorreo;
    }

    public JButton getaExpediente() {
        return aExpediente;
    }

    public void setaExpediente(JButton aExpediente) {
        this.aExpediente = aExpediente;
    }

    public JButton getaPrimeraVez1() {
        return aPrimeraVez1;
    }

    public void setaPrimeraVez1(JButton aPrimeraVez1) {
        this.aPrimeraVez1 = aPrimeraVez1;
    }

    public JButton getaSalir() {
        return aSalir;
    }

    public void setaSalir(JButton aSalir) {
        this.aSalir = aSalir;
    }

    public JButton getaSomatometria() {
        return aSomatometria;
    }

    public void setaSomatometria(JButton aSomatometria) {
        this.aSomatometria = aSomatometria;
    }

    public JToolBar getBarraMenu() {
        return barraMenu;
    }

    public void setBarraMenu(JToolBar barraMenu) {
        this.barraMenu = barraMenu;
    }

    public JButton getCerrar() {
        return cerrar;
    }

    public void setCerrar(JButton cerrar) {
        this.cerrar = cerrar;
    }

    public JButton getdBotonCSalir() {
        return dBotonCSalir;
    }

    public void setdBotonCSalir(JButton dBotonCSalir) {
        this.dBotonCSalir = dBotonCSalir;
    }

    public JButton getdBotonExit() {
        return dBotonExit;
    }

    public void setdBotonExit(JButton dBotonExit) {
        this.dBotonExit = dBotonExit;
    }

    public JDialog getdSalida() {
        return dSalida;
    }

    public void setdSalida(JDialog dSalida) {
        this.dSalida = dSalida;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JInternalFrame getjInternalFrame1() {
        return jInternalFrame1;
    }

    public void setjInternalFrame1(JInternalFrame jInternalFrame1) {
        this.jInternalFrame1 = jInternalFrame1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getlUsuario() {
        return lUsuario;
    }

    public void setlUsuario(String usuario) {
        lUsuario.setText(usuario);
    }

    public JMenuItem getmAcercaDe() {
        return mAcercaDe;
    }

    public void setmAcercaDe(JMenuItem mAcercaDe) {
        this.mAcercaDe = mAcercaDe;
    }

    public JMenuItem getmAgenda() {
        return mAgenda;
    }

    public void setmAgenda(JMenuItem mAgenda) {
        this.mAgenda = mAgenda;
    }

    public JButton getmAyuda() {
        return mAyuda;
    }

    public void setmAyuda(JButton mAyuda) {
        this.mAyuda = mAyuda;
    }

    public JMenuItem getmBitacoraAcceso() {
        return mBitacoraAcceso;
    }

    public void setmBitacoraAcceso(JMenuItem mBitacoraAcceso) {
        this.mBitacoraAcceso = mBitacoraAcceso;
    }

    public JMenuItem getmCertificado() {
        return mCertificado;
    }

    public void setmCertificado(JMenuItem mCertificado) {
        this.mCertificado = mCertificado;
    }

    public JMenuItem getmConfiguraCorreo() {
        return mConfiguraCorreo;
    }

    public void setmConfiguraCorreo(JMenuItem mConfiguraCorreo) {
        this.mConfiguraCorreo = mConfiguraCorreo;
    }

    public JMenuItem getmConfiguraUsuarios() {
        return mConfiguraUsuarios;
    }

    public void setmConfiguraUsuarios(JMenuItem mConfiguraUsuarios) {
        this.mConfiguraUsuarios = mConfiguraUsuarios;
    }

    public JButton getmConfiguracion() {
        return mConfiguracion;
    }

    public void setmConfiguracion(JButton mConfiguracion) {
        this.mConfiguracion = mConfiguracion;
    }

    public JButton getmConsultas() {
        return mConsultas;
    }

    public void setmConsultas(JButton mConsultas) {
        this.mConsultas = mConsultas;
    }

    public JMenuItem getmCorreo() {
        return mCorreo;
    }

    public void setmCorreo(JMenuItem mCorreo) {
        this.mCorreo = mCorreo;
    }

    public JMenuItem getmCxc() {
        return mCxc;
    }

    public void setmCxc(JMenuItem mCxc) {
        this.mCxc = mCxc;
    }

    public JMenuItem getmDatosFiscales() {
        return mDatosFiscales;
    }

    public void setmDatosFiscales(JMenuItem mDatosFiscales) {
        this.mDatosFiscales = mDatosFiscales;
    }

    public JMenuItem getmDisenosPlantillas() {
        return mDisenosPlantillas;
    }

    public void setmDisenosPlantillas(JMenuItem mDisenosPlantillas) {
        this.mDisenosPlantillas = mDisenosPlantillas;
    }

    public JMenuItem getmErrores() {
        return mErrores;
    }

    public void setmErrores(JMenuItem mErrores) {
        this.mErrores = mErrores;
    }

    public JMenuItem getmExpedientes() {
        return mExpedientes;
    }

    public void setmExpedientes(JMenuItem mExpedientes) {
        this.mExpedientes = mExpedientes;
    }

    public JMenuItem getmFacturas() {
        return mFacturas;
    }

    public void setmFacturas(JMenuItem mFacturas) {
        this.mFacturas = mFacturas;
    }

    public JButton getmFinanzas() {
        return mFinanzas;
    }

    public void setmFinanzas(JButton mFinanzas) {
        this.mFinanzas = mFinanzas;
    }

    public JButton getmHerramientas() {
        return mHerramientas;
    }

    public void setmHerramientas(JButton mHerramientas) {
        this.mHerramientas = mHerramientas;
    }

    public JMenuItem getmNotasRemision() {
        return mNotasRemision;
    }

    public void setmNotasRemision(JMenuItem mNotasRemision) {
        this.mNotasRemision = mNotasRemision;
    }

    public JButton getmPacientes() {
        return mPacientes;
    }

    public void setmPacientes(JButton mPacientes) {
        this.mPacientes = mPacientes;
    }

    public JMenuItem getmPreguntasFrecuentes() {
        return mPreguntasFrecuentes;
    }

    public void setmPreguntasFrecuentes(JMenuItem mPreguntasFrecuentes) {
        this.mPreguntasFrecuentes = mPreguntasFrecuentes;
    }

    public JMenuItem getmPrimeraVez() {
        return mPrimeraVez;
    }

    public void setmPrimeraVez(JMenuItem mPrimeraVez) {
        this.mPrimeraVez = mPrimeraVez;
    }

    public JMenuItem getmReportes() {
        return mReportes;
    }

    public void setmReportes(JMenuItem mReportes) {
        this.mReportes = mReportes;
    }

    public JMenuItem getmRespaldos() {
        return mRespaldos;
    }

    public void setmRespaldos(JMenuItem mRespaldos) {
        this.mRespaldos = mRespaldos;
    }

    public JButton getmSalir() {
        return mSalir;
    }

    public void setmSalir(JButton mSalir) {
        this.mSalir = mSalir;
    }

    public JMenuItem getmSomato() {
        return mSomato;
    }

    public void setmSomato(JMenuItem mSomato) {
        this.mSomato = mSomato;
    }

    public JMenuItem getmTopicosAyuda() {
        return mTopicosAyuda;
    }

    public void setmTopicosAyuda(JMenuItem mTopicosAyuda) {
        this.mTopicosAyuda = mTopicosAyuda;
    }

    public JMenuItem getmVideotutoriales() {
        return mVideotutoriales;
    }

    public void setmVideotutoriales(JMenuItem mVideotutoriales) {
        this.mVideotutoriales = mVideotutoriales;
    }

    public JButton getMinimizar() {
        return minimizar;
    }

    public void setMinimizar(JButton minimizar) {
        this.minimizar = minimizar;
    }

    public JPanel getPanelMenu() {
        return panelMenu;
    }

    public void setPanelMenu(JPanel panelMenu) {
        this.panelMenu = panelMenu;
    }

    public JPopupMenu getPumAyuda() {
        return pumAyuda;
    }

    public void setPumAyuda(JPopupMenu pumAyuda) {
        this.pumAyuda = pumAyuda;
    }

    public JPopupMenu getPumConfiguracion() {
        return pumConfiguracion;
    }

    public void setPumConfiguracion(JPopupMenu pumConfiguracion) {
        this.pumConfiguracion = pumConfiguracion;
    }

    public JPopupMenu getPumConsultas() {
        return pumConsultas;
    }

    public void setPumConsultas(JPopupMenu pumConsultas) {
        this.pumConsultas = pumConsultas;
    }

    public JPopupMenu getPumFinanzas() {
        return pumFinanzas;
    }

    public void setPumFinanzas(JPopupMenu pumFinanzas) {
        this.pumFinanzas = pumFinanzas;
    }

    public JPopupMenu getPumHerramientas() {
        return pumHerramientas;
    }

    public void setPumHerramientas(JPopupMenu pumHerramientas) {
        this.pumHerramientas = pumHerramientas;
    }

    public JPopupMenu getPumPaciente() {
        return pumPaciente;
    }

    public void setPumPaciente(JPopupMenu pumPaciente) {
        this.pumPaciente = pumPaciente;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public void setTitulo(JLabel titulo) {
        this.titulo = titulo;
    }

    public JLabel getTitulo1() {
        return titulo1;
    }

    public Sesion getSesion() {
        return sesion;
    }

    public void setSesion(Sesion sesion) {
        this.sesion = sesion;
    }
    
    

/**
 * ----------------------------------------------------------------------------------------
 */ 
    
    
    
    private int x, y;
    ConectorVistas cv;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aAgenda;
    private javax.swing.JButton aCorreo;
    private javax.swing.JButton aExpediente;
    private javax.swing.JButton aPrimeraVez1;
    private javax.swing.JButton aSalir;
    private javax.swing.JButton aSomatometria;
    private javax.swing.JToolBar barraMenu;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton dBotonCSalir;
    private javax.swing.JButton dBotonExit;
    private javax.swing.JDialog dSalida;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JMenuItem mAcercaDe;
    private javax.swing.JMenuItem mAgenda;
    private javax.swing.JButton mAyuda;
    private javax.swing.JMenuItem mBitacoraAcceso;
    private javax.swing.JMenuItem mCertificado;
    private javax.swing.JMenuItem mConfiguraCorreo;
    private javax.swing.JMenuItem mConfiguraUsuarios;
    private javax.swing.JButton mConfiguracion;
    private javax.swing.JButton mConsultas;
    private javax.swing.JMenuItem mCorreo;
    private javax.swing.JMenuItem mCxc;
    private javax.swing.JMenuItem mDatosFiscales;
    private javax.swing.JMenuItem mDisenosPlantillas;
    private javax.swing.JMenuItem mErrores;
    private javax.swing.JMenuItem mExpedientes;
    private javax.swing.JMenuItem mFacturas;
    private javax.swing.JButton mFinanzas;
    private javax.swing.JButton mHerramientas;
    private javax.swing.JMenuItem mNotasRemision;
    private javax.swing.JButton mPacientes;
    private javax.swing.JMenuItem mPreguntasFrecuentes;
    private javax.swing.JMenuItem mPrimeraVez;
    private javax.swing.JMenuItem mReportes;
    private javax.swing.JMenuItem mRespaldos;
    private javax.swing.JButton mSalir;
    private javax.swing.JMenuItem mSomato;
    private javax.swing.JMenuItem mTopicosAyuda;
    private javax.swing.JMenuItem mVideotutoriales;
    private javax.swing.JButton minimizar;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPopupMenu pumAyuda;
    private javax.swing.JPopupMenu pumConfiguracion;
    private javax.swing.JPopupMenu pumConsultas;
    private javax.swing.JPopupMenu pumFinanzas;
    private javax.swing.JPopupMenu pumHerramientas;
    private javax.swing.JPopupMenu pumPaciente;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}