/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solinfori.vistas.Paciente;

/**
 *
 * @author Dell Optiplex 7010
 */
public class Expedientes extends javax.swing.JInternalFrame {

    private static Expedientes expedientes;
    /**
     * Creates new form Expedientes
     */
    public Expedientes() {
        initComponents();
    }
    
    public static Expedientes getInstancia(){
        if(expedientes == null){
            expedientes = new Expedientes();
        }
        return expedientes;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(241, 241, 242));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 241, 242), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Expediente Médico");
        setAutoscrolls(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x20.png"))); // NOI18N
        setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
