/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solinfori.vistas.Paciente.primeraVez;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import solinfori.controlador.coordinadores.CoordinaPrimeraVez;
import solinfori.controlador.coordinadores.CoordinaRegistrosPacientes;
import solinfori.controlador.coordinadores.CoordinaSomatometriaYSV;
import solinfori.vistas.Paciente.PrimeraVez;
import solinfori.vistas.Paciente.SomatometriaYSV;



/**
 *
 * @author Maribel Marroquín - SOLINFORI
 */
public class RegistrosPacientes extends javax.swing.JInternalFrame {

    //private final Sesion sesion;
    private CoordinaRegistrosPacientes coordinacion;
    private boolean security = true;
    private static JInternalFrame internal;

    /**
     * Creates new form RegistrosPacientes
     */
    public RegistrosPacientes(JInternalFrame internal) {
//      this.sesion = sesion;
        initComponents();
        coordinacion = new CoordinaRegistrosPacientes();
        coordinacion.alternadorBusqueda(this);
        this.internal = internal;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFiltrarPorClave = new javax.swing.JTextField();
        txtFiltrarPorNombre = new javax.swing.JTextField();
        txtFiltrarPorApePat = new javax.swing.JTextField();
        txtFiltrarPorApeMat = new javax.swing.JTextField();
        txtFiltrarPorEmail = new javax.swing.JTextField();
        btnBuscarPaciente = new javax.swing.JButton();
        btnLimpiarListado = new javax.swing.JButton();
        dchFiltrarPorFechaNac = new com.toedter.calendar.JDateChooser();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 149, 173), 2, true));
        setClosable(true);
        setTitle("Búsqueda de Paciente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/iconos_SIACMed_pequeños_x20.png"))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTablePacientes = new JTable(){
            public boolean isCellEditable(int row, int column){
                for(int i=0; i < jTablePacientes.getRowCount(); i++){
                    if(row == i){
                        return false;
                    }
                }
                return true;
            }
        };
        jTablePacientes.setForeground(new java.awt.Color(102, 102, 102));
        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Fecha de nacimiento", "Correo electrónico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTablePacientes.setGridColor(new java.awt.Color(25, 149, 173));
        jTablePacientes.setName(""); // NOI18N
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Por nombre:");

        jLabel2.setText("Por apellido paterno:");

        jLabel3.setText("Por apellido materno:");

        jLabel4.setText("Por fecha de nacimiento:");

        jLabel5.setText("Por clave:");

        jLabel8.setText("Por correo electrónico:");

        txtFiltrarPorClave.setForeground(new java.awt.Color(102, 102, 102));

        txtFiltrarPorNombre.setForeground(new java.awt.Color(102, 102, 102));

        txtFiltrarPorApePat.setForeground(new java.awt.Color(102, 102, 102));

        txtFiltrarPorApeMat.setForeground(new java.awt.Color(102, 102, 102));

        txtFiltrarPorEmail.setForeground(new java.awt.Color(102, 102, 102));

        btnBuscarPaciente.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton.png"))); // NOI18N
        btnBuscarPaciente.setText("Buscar");
        btnBuscarPaciente.setBorder(null);
        btnBuscarPaciente.setBorderPainted(false);
        btnBuscarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPaciente.setFocusable(false);
        btnBuscarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarPaciente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton_clickeado.png"))); // NOI18N
        btnBuscarPaciente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton_selected.png"))); // NOI18N
        btnBuscarPaciente.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton_selected.png"))); // NOI18N
        btnBuscarPaciente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton_selected.png"))); // NOI18N
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        btnLimpiarListado.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiarListado.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton.png"))); // NOI18N
        btnLimpiarListado.setText("Limpiar búsqueda");
        btnLimpiarListado.setBorder(null);
        btnLimpiarListado.setBorderPainted(false);
        btnLimpiarListado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarListado.setFocusPainted(false);
        btnLimpiarListado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiarListado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton_clickeado.png"))); // NOI18N
        btnLimpiarListado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton_selected.png"))); // NOI18N
        btnLimpiarListado.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton_selected.png"))); // NOI18N
        btnLimpiarListado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/solinfori/img/buttons/boton_selected.png"))); // NOI18N
        btnLimpiarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarListadoActionPerformed(evt);
            }
        });

        dchFiltrarPorFechaNac.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiltrarPorClave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFiltrarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFiltrarPorApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFiltrarPorApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFiltrarPorEmail)
                            .addComponent(dchFiltrarPorFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarPaciente)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarListado)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(txtFiltrarPorClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtFiltrarPorApePat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dchFiltrarPorFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFiltrarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtFiltrarPorApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtFiltrarPorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPaciente)
                    .addComponent(btnLimpiarListado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:
        //coordinacion.listarPacientes(this);
        coordinacion.alternadorBusqueda(this);
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        // TODO add your handling code here:
        if(internal.getName().equals("primeravez")){
            PrimeraVez pv = (PrimeraVez) internal;
            CoordinaPrimeraVez coordinaPrimeraVez = new CoordinaPrimeraVez(pv, pv.getSesion());
            if(evt.getClickCount()==2){
                //JOptionPane.showMessageDialog(rootPane, "Haz dado click en la fila No.: "+jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 0) , title, HEIGHT);
                coordinaPrimeraVez.retornarPaciente(jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 0).toString());
                this.dispose();
            }
        }else if(internal.getName().equals("somatosv")){
            SomatometriaYSV ssv = (SomatometriaYSV) internal;
            CoordinaSomatometriaYSV coordinaSomatometriaYSV = new CoordinaSomatometriaYSV(ssv);
            if(evt.getClickCount()==2){
                //JOptionPane.showMessageDialog(rootPane, "Haz dado click en la fila No.: "+jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 0) , title, HEIGHT);
                coordinaSomatometriaYSV.retornarPaciente(jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 0).toString());
                this.dispose();
            }
            
        }
        
        
        
    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void btnLimpiarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarListadoActionPerformed
        // TODO add your handling code here:
        coordinacion.limpiarBusqueda(this);
    }//GEN-LAST:event_btnLimpiarListadoActionPerformed

    
    //SET's y GET's para manipular componentes del jFrame ---------------------------------------------
    
    public JButton getBtnBuscarPaciente() {
        return btnBuscarPaciente;
    }

    public void setBtnBuscarPaciente(JButton btnBuscarPaciente) {
        this.btnBuscarPaciente = btnBuscarPaciente;
    }

    public JDateChooser getjDateChooser1() {
        return dchFiltrarPorFechaNac;
    }

    public void setjDateChooser1(JDateChooser jDateChooser1) {
        this.dchFiltrarPorFechaNac = jDateChooser1;
    }

    public JTable getjTablePacientes() {
        return jTablePacientes;
    }

    public void setjTablePacientes(JTable jTablePacientes) {
        this.jTablePacientes = jTablePacientes;
    }

    public JDateChooser getDchFiltrarPorFechaNac() {
        return dchFiltrarPorFechaNac;
    }

    public void setDchFiltrarPorFechaNac(JDateChooser dchFiltrarPorFechaNac) {
        this.dchFiltrarPorFechaNac = dchFiltrarPorFechaNac;
    }

    public JTextField getTxtFiltrarPorApeMat() {
        return txtFiltrarPorApeMat;
    }

    public void setTxtFiltrarPorApeMat(JTextField txtFiltrarPorApeMat) {
        this.txtFiltrarPorApeMat = txtFiltrarPorApeMat;
    }

    public JTextField getTxtFiltrarPorApePat() {
        return txtFiltrarPorApePat;
    }

    public void setTxtFiltrarPorApePat(JTextField txtFiltrarPorApePat) {
        this.txtFiltrarPorApePat = txtFiltrarPorApePat;
    }

    public JTextField getTxtFiltrarPorClave() {
        return txtFiltrarPorClave;
    }

    public void setTxtFiltrarPorClave(JTextField txtFiltrarPorClave) {
        this.txtFiltrarPorClave = txtFiltrarPorClave;
    }

    public JTextField getTxtFiltrarPorEmail() {
        return txtFiltrarPorEmail;
    }

    public void setTxtFiltrarPorEmail(JTextField txtFiltrarPorEmail) {
        this.txtFiltrarPorEmail = txtFiltrarPorEmail;
    }

    public JTextField getTxtFiltrarPorNombre() {
        return txtFiltrarPorNombre;
    }

    public void setTxtFiltrarPorNombre(JTextField txtFiltrarPorNombre) {
        this.txtFiltrarPorNombre = txtFiltrarPorNombre;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnLimpiarListado;
    private com.toedter.calendar.JDateChooser dchFiltrarPorFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField txtFiltrarPorApeMat;
    private javax.swing.JTextField txtFiltrarPorApePat;
    private javax.swing.JTextField txtFiltrarPorClave;
    private javax.swing.JTextField txtFiltrarPorEmail;
    private javax.swing.JTextField txtFiltrarPorNombre;
    // End of variables declaration//GEN-END:variables
}
